CREATE DATABASE if NOT EXISTS practicaUsuarios;
USE practicaUsuarios;

CREATE OR REPLACE TABLE usuarios(
correo VARCHAR(40) PRIMARY KEY,
nombreUsuario VARCHAR(20) NOT NULL UNIQUE,
contrasenia VARCHAR(30) NOT NULL);

CREATE OR REPLACE TABLE login(
id_login INT(5) PRIMARY KEY AUTO_INCREMENT,
correo VARCHAR(40),
fechaLogin DATETIME DEFAULT NOW(),
CONSTRAINT loginUsuarioFK FOREIGN KEY (correo)
REFERENCES usuarios(correo)
ON UPDATE CASCADE
ON DELETE RESTRICT);